<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Top articles</title>
<style>
	* { 
	  margin: 0; 
	  padding: 0; 
     }
     body { 
	   font: 14px/1.4 Georgia, Serif; 
     }
    #page-wrap {
	  margin: 50px;
    }
    p {
	 margin: 20px 0; 
    }

	/* 
	Generic Styling, for Desktops/Laptops 
	*/
	table { 
		width: 100%; 
		border-collapse: collapse; 
	}
	/* Zebra striping */
	tr:nth-of-type(odd) { 
		background: #eee; 
	}
	th { 
		background: #333; 
		color: white; 
		font-weight: bold; 
		cursor: s-resize;
		background-repeat: no-repeat;
        background-position: 3% center;
	}
	td, th { 
		padding: 6px; 
		border: 1px solid #ccc; 
		text-align: left; 
	}
	
	th.des:after {
      content: "\21E9";
    }
    
    th.aes:after {
      content: "\21E7";
    }
	
	/* 
	Max width before this PARTICULAR table gets nasty
	This query will take effect for any screen smaller than 760px
	and also iPads specifically.
	*/
	@media 
	only screen and (max-width: 760px),
	(min-device-width: 768px) and (max-device-width: 1024px)  {
	
		/* Force table to not be like tables anymore */
		table, thead, tbody, th, td, tr { 
			display: block; 
		}
		
		/* Hide table headers (but not display: none;, for accessibility) */
		thead tr { 
			position: absolute;
			top: -9999px;
			left: -9999px;
		}
		
		tr { border: 1px solid #ccc; }
		
		td { 
			/* Behave  like a "row" */
			border: none;
			border-bottom: 1px solid #eee; 
			position: relative;
			padding-left: 50%; 
		}
		
		td:before { 
			/* Now like a table header */
			position: absolute;
			/* Top/left values mimic padding */
			top: 6px;
			left: 6px;
			width: 45%; 
			padding-right: 10px; 
			white-space: nowrap;
		}
		
		/*
		Label the data
		*/
		td:before {
		  content: attr(data-th) ": ";
          font-weight: bold;
          width: 6.5em;
          display: inline-block;
		}
	}
	
	/* Smartphones (portrait and landscape) ----------- */
	@media only screen
	and (min-device-width : 320px)
	and (max-device-width : 480px) {
		body { 
			padding: 0; 
			margin: 0; 
			width: 320px; }
		}
	
	/* iPads (portrait and landscape) ----------- */
	@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
		body { 
			width: 495px; 
		}
	}
	
	</style>
</head>
<body>


<script src="https://d3js.org/d3.v3.js"></script>

<div id="table_wrap" style="width=200%; margin-right:5px;">
        <h3>Top cited articles from top cited authors (at least 10 citations)</h3>
        <p>Click headers to sort by ascending/descending</p>
        <p>Double click the table body to go see a wordcloud of keywords</p>
        <table></table>
    </div>
<script>
var thfill = [
	{ "eid":"2-s2.0-33646019818", "abstract":"In this experiment, we examine effects of television dramas on support for controversial public policies (gay marriage and the death penalty) and explore mechanisms that may explain such effects. The dramas influenced support for death penalty but not gay marriage. As predicted, exposure to the relevant drama eliminated the relationship between prior ideology (conceptualized as a continuous variable) and death penalty support. Moreover, the valence of the relationship between prior (increasingly liberal) ideology and salience of a relevant value (perceived importance of a safe and crime-free society) went from negative in the comparison condition to positive after exposure to the relevant drama. These and other results suggest that a television narrative can influence policy support by reframing the dramatic situation to reduce the effect of prior ideology and values and by minimizing processing of the story as intentionally persuasive discourse. © 2006 International Communication Association.", "count":39, "keywords":[ ] }, 
	{ "eid":"2-s2.0-0035632513", "abstract":"This study of the main evening television news programs in four European countries focuses on the framing of news surrounding a major European event, the January 1, 1999, introduction of the common European currency, the euro. We investigated the visibility of political and economic news in general and of the launch of the euro in particular. We found variations across countries in the emphasis on political and economic news, with the proportion of the newscast normally devoted to these subjects ranging from 45% to 60%. Journalists in all countries were more likely to emphasize conflict (rather than economic consequences) in framing general political and economic news. In the coverage of the launch of the euro, there was a greater emphasis on framing the news in terms of economic consequences. The findings are discussed in terms of influences on framing practices internal and external to journalism and the value of the cross-national comparative approach.", "count":34, "keywords":["Comparative", " Conflict", " Content analysis", " Economy", " Euro", " European integration", " Framing", " News" ] },
	{ "eid":"2-s2.0-79959561294", "abstract":"The role of traditional media and the Internet in relation to young people's political participation has attracted a great deal of scholarly attention. Starting from a notion of differential media use and an encompassing notion of political participation, this article tests the relationships between media use (newspaper, television, and Internet) and offline and online forms of political participation. Findings from a national survey (n = 2,409, age 16 to 24) reveal that a variety of Internet uses are positively related with different forms of political participation, whereas the relationship between most uses of traditional media and participation are weak, albeit positive. The study rejects the predictive power of duration of media use but finds support for the type of media use. Positive relationships between online communication and noninformational uses of the Internet vis-à-vis participation are found. The research demonstrates how a wider and more contemporary conception of political participation, together with more detailed measures of media use, can help to gain better insight in the roles media can play in affecting participatory behavior among the Internet generation. © The Author(s) 2011.", "count":24, "keywords":[ "Internet", " media use", " political participation", " youth" ] },
	{ "eid":"2-s2.0-0242719782", "abstract":"Theory and research on media violence provides evidence that aggressive youth seek out media violence and that media violence prospectively predicts aggression in youth. The authors argue that both relationships, when modeled over time, should be mutually reinforcing, in what they call a downward spiral model. This study uses multilevel modeling to examine individual growth curves in aggressiveness and violent media use. The measure of use of media violence included viewing action films, playing violent computer and video games, and visiting violence-oriented Internet sites by students from 20 middle schools in 10 different regions in the United States. The findings appear largely consistent with the proposed model. In particular, concurrent effects of aggressiveness on violent-media use and concurrent and lagged effects of violent media use on aggressiveness were found. The implications of this model for theorizing about media effects on youth, and for bridging active audience with media effects perspectives, are discussed.", "count":24, "keywords":[ "Aggression", " Media effects", " Selective exposure", " Violent media content" ] }, 
	{ "eid":"2-s2.0-33947242372", "abstract":"This manuscript reports 2 experiments that were conducted to test and extend the work of J. P. Dillard and L. Shen (2005) examining the cognitive and affective processes involved in psychological reactance. In particular, the studies reported here (a) examined the best-fitting model of reactance processes and (b) tested 3 factors that may affect reactance including argument quality, severity of the consequences associated with the message topic, and magnitude of the request made in the message. The results showed that the intertwined cognitive-affective model was the best-fitting model of reactance processes. Magnitude of the request was the only variable that affected reactance. The implications of these findings for research on reactance and persuasive health campaigns are discussed. © 2007 International Communication Association.", "count":20, "keywords":[ ] },
	{ "eid":"2-s2.0-78649523462", "abstract":"The amount of cancer-related information available in the media and other sources continues to increase each year. We wondered how people make use of such content in making specific health decisions. We studied both the information they actively seek (seeking) and that which they encounter in a less purposive way (scanning) through a nationally representative survey of adults aged 40-70 years (n=2,489) focused on information use around three prevention behaviors (dieting, fruit and vegetable consumption, and exercising) and three screening test behaviors (prostate-specific antigen, colonoscopy, mammogram). Overall, respondents reported a great deal of scanning and somewhat less seeking (on average 62% versus 28% for each behavior), and they used a range of sources including mass media, interpersonal conversations, and the Internet, alongside physicians. Seeking was predicted by female gender, age of 55-64 vs. 40-44, higher education, Black race and Hispanic ethnicity, and being married. Scanning was predicted by older age, female gender, and education. Respondents were fairly consistent in their place on a typology of scanning and seeking across behaviors. Seeking was associated with all six behaviors, and scanning was associated with three of six behaviors. Copyright © Taylor & Francis Group, LLC.", "count":18, "keywords":[ ] },
	{ "eid":"2-s2.0-79958235018", "abstract":"Informed by theory and research on attributions and narrative persuasion, we compared the effectiveness of narrative and nonnarrative messages in changing attributions of responsibility for causes and solutions related to obesity in the United States. We randomly assigned 500 adults to view one of three messages (narrative, evidence, and a hybrid of the two) emphasizing environmental causes of obesity, or a no-exposure control condition. The narrative condition increased the belief that societal actors (government, employers) are responsible for addressing obesity, but only among liberals. This pattern of results was partially explained by the success of the narrative condition in reducing reactive counterarguing, relative to the evidence condition, among liberals. We conclude with theoretical and practical implications. © 2011 International Communication Association.", "count":17, "keywords":[ ] },
	{ "eid":"2-s2.0-33947194800", "abstract":"The effects of the attitudinal, normative, and perceived behavioral control (PBC) components of the theory of planned behavior and personal- and societal-level descriptive and injunctive norms were investigated with regard to their impact on the intent to enroll on a state organ-donor registry and the intent to engage in family discussion about organ donation. The results indicated that the 5 types of norms were distinct across the 2 behaviors. Different types of norms served as predictors and as moderators for the 2 behavioral intentions. The effects of attitudes toward each behavior and PBC were moderated by personal descriptive norms for behavioral intention to sign and by subjective norms for behavioral intention to talk with family. © 2007 International Communication Association.", "count":17, "keywords":[ ] },
	{ "eid":"2-s2.0-70449564781", "abstract":"This study tested two models of instructor credibility as a potential mediator of instructors' prosocial communication behaviors (e.g., confirmation, clarity, and nonverbal immediacy) and students' learning outcomes. Participants included 1,416 undergraduate students from four different institutions across the United States. Results of structural equation modeling provided greater support for the partial mediation model, whereby credibility partially mediated the effects of teacher confirmation and clarity on learning outcomes, though it fully mediated the effects of nonverbal immediacy. When combined, students' perceptions of all three prosocial behaviors accounted for 66% and 57% of the variance in credibility and learning outcomes, respectively. Among the more important implications of this research is the finding that confirming behaviors and clarity have both direct and indirect effects on student learning. © 2009 National Communication Association.", "count":16, "keywords":["Instructor credibility", " Learning outcomes", " Nonverbal immediacy", " Teacher clarity", " Teacher confirmation" ] },
	{ "eid":"2-s2.0-50249125392", "abstract":"A content analysis of cancer news coverage in a sample of local and national newspapers, television, and magazines was conducted for the years 2002 and 2003. Analyses compared proportions of mentions of cancer sites with proportional contribution to cancer incidence and mortality based on available epidemiological estimates. Analyses also examined relative attention provided to prevention, detection, treatment, causes, and outcomes of various cancers. Results indicated that coverage reflected incidence rates more closely than they did mortality rates, but in both cases coverage under-represented the contribution of lung cancer to morbidity and mortality and over-represented the contribution of breast cancer. Of greater public health concern was the limited coverage of prevention and detection even for highly preventable or relatively easily detected cancers. Implications of findings are discussed. Copyright © Taylor & Francis Group, LLC.", "count":16, "keywords":[ ] },
	{ "eid":"2-s2.0-35348838932", "abstract":"As medical information becomes increasingly available and individuals take a more active role in managing their personal health, it is essential for scholars to better understand the general public's information-seeking behavior. The study reported here explores the use of the World Wide Web to seek health information in a contemporary information-media environment. Drawing from uses and gratifications theory and the comprehensive model of health information seeking, perceptions of traditional information sources (e.g., mass media, one's health care provider, etc.) are posited to predict use of the Web to seek health information and perceptions of information acquired from searches. Data from the Health Information National Trends Survey (HINTS; N = 3982) were analyzed to test study hypotheses. Trust in information-oriented media, entertainment-oriented media, and one's health care provider all predicted Web use behavior and perceptions. The implications of the findings for research on information seeking and the role of the Web in patient empowerment are discussed. Copyright © Taylor & Francis Group, LLC.", "count":16, "keywords":[ ] },
	{ "eid":"2-s2.0-72949113837", "abstract":"This study addresses the frequency and the distribution of reported lying in the adult population. A national survey asked 1,000 U.S. adults to report the number of lies told in a 24-hour period. Sixty percent of subjects report telling no lies at all, and almost half of all lies are told by only 5% of subjects; thus, prevalence varies widely and most reported lies are told by a few prolific liars. The pattern is replicated in a reanalysis of previously published research and with a student sample. Substantial individual differences in lying behavior have implications for the generality of truth-lie base rates in deception detection experiments. Explanations concerning the nature of lying and methods for detecting lies need to account for this variation. © 2010 International Communication Association.", "count":15, "keywords":[ ] },
	{ "eid":"2-s2.0-66749171839", "abstract":"This article reports a meta-analysis of 28 studies examining the health-related outcomes associated with participation in a formal computer-mediated support group (CMSG) intervention. In particular, health outcomes related to social support were assessed and four group-level characteristics of CMSGs were tested as potential moderators of intervention effectiveness. The results show that participating in a CMSG intervention - comprised of educational and group communication components - led to increased social support, decreased depression, increased quality of life, and increased self-efficacy to manage one's health condition. Changes in health outcomes were moderated by group size, the nature of the communication channels available, and the duration of the CMSG intervention. © 2009 International Communication Association.", "count":15, "keywords":[ ] },
	{ "eid":"2-s2.0-33646776417", "abstract":"Drawing on a survey of 745 Dutch adolescents ages 13 to 18, the authors investigated (a) the occurrence and frequency of adolescents' exposure to sexually explicit material on the Internet and (b) the correlates of this exposure. Seventy-one percent of the male adolescents and 40% of the female adolescents had been exposed to some kind of online sexually explicit material in the 6 months prior to the interview. Adolescents were more likely to be exposed to sexually explicit material online if they were male, were high sensation seekers, were less satisfied with their lives, were more sexually interested, used sexual content in other media more often, had a fast Internet connection, and had friends that were predominantly younger. Among male adolescents, a more advanced pubertal status was also associated with more frequent exposure to online sexually explicit material. Among female adolescents, greater sexual experience decreased exposure to online sexually explicit material. © 2006 Sage Publications.", "count":14, "keywords":[ "Gender differences", " Internet use", " Life satisfaction", " Pornography", " Sensation seeking" ] },
	{ "eid":"2-s2.0-84875785040", "abstract":"In this theoretical article, we introduce the Differential Susceptibility to Media Effects Model (DSMM), a new, integrative model to improve our understanding of media effects. The DSMM organizes, integrates, and extends the insights developed in earlier microlevel media-effects theories. It distinguishes 3 types of susceptibility to media effects: dispositional, developmental, and social susceptibility. Using the analogy of a mixing console, the DSMM proposes 3 media response states that mediate media effects: cognitive, emotional, and excitative. The assumptions on which the DSMM is based together explain (a) why some individuals are more highly susceptible to media effects than others, (b) how and why media influence those individuals, and (c) how media effects can be enhanced or counteracted. © 2013 International Communication Association.", "count":14, "keywords":[ ] },
	{ "eid":"2-s2.0-33645075731", "abstract":"Fast-paced and arousing anti-drug ads, considered to have high perceived message sensation value (PMSV), enhance message processing and reduce drug use among young adults. Studies have yet to explore the relationship between specific, PMSV-enhancing message features and outcomes related to persuasion. Messaris (1997) concept of syntactic indeterminacy provides one plausible explanation for why message features contained in high PMSV ads might enhance message processing and subsequent changes in attitudes and behavior. The study explored this explanation by coding specific anti-tobacco ads for PMSV-enhancing features, merging these codes to a telephone survey among teens, and testing the relationship between message features and processing. The number of unrelated cuts and the use of suspenseful features (intense imagery and a second-half punch) increased message processing among older teens. An additive index comprised of these features was associated with message processing among both younger and older teens. Theoretical and practical implications are discussed.", "count":13, "keywords":[ "Campaigns", " Message Features", " Message Processing", " Message Sensation Value", " Syntactic Indeterminacy" ] },
	{ "eid":"2-s2.0-84865085509", "abstract":"Right before the 2008 U.S. presidential election, this 2-session online field study examined consequences of selective exposure to political messages on accessibility of attitudes and of partisanship. In the first session, participants indicated attitudes toward political issues and their partisanship, which allowed measuring accessibility of attitudes and of partisanship. In the second session, participants browsed articles. Four issues were covered by 8 articles, with 2 articles featuring opposing perspectives. Selective exposure was unobtrusively logged. Finally, participants completed measures for attitudes and partisanship again. Selective exposure to attitude-consistent articles was linked to greater attitude accessibility. The indirect impact of selective exposure on partisanship accessibility through attitude accessibility was significant. © 2012 International Communication Association.", "count":12, "keywords":[ ] },
	{ "eid":"2-s2.0-33745566828", "abstract":"This study explored the associations among perceived teacher confirmation behaviors (i.e., demonstrating interest, responding to questions, and teaching style) and student perceptions of teacher power use (i.e., coercive, reward, expert, legitimate, and referent power). Participants included 656 students from two Midwestern universities. Results revealed that perceived teacher confirmation accounts for 20% of the variance in student perceptions of teacher power. Further, perceived teacher confirmation behaviors were more closely associated with student perceptions of teacher pro-social power use than with anti-social power use. Specifically, post hoc analyses revealed that perceived confirmation behaviors are more closely associated with student ratings of expert and reward power than ratings of referent and coercive power.", "count":11, "keywords":[ "Demonstrated Interest", " Responds to Questions", " Teacher Confirmation", " Teacher Power", " Teaching Style"] },
	{ "eid":"2-s2.0-33748866486", "abstract":"This study tested two theoretical models of perceived understanding as a potential mediator of perceived teacher confirmation and students' ratings of instruction. Participants included 651 undergraduate students who completed survey measures. Results of structural equation modeling provided greater support for the confirmation process model, whereby students' perceived understanding partially mediated the effects of perceived teacher confirmation on both teacher credibility and evaluations. Further, perceived teacher confirmation accounted for 64% of the variance in perceived understanding, and both confirmation and understanding accounted for 70% and 72% of the variances in teacher evaluations and credibility, respectively. Among the more important implications of this research is the finding that confirming behaviors have both direct and indirect effects on students' ratings of instruction. © 2006 National Communication Association.", "count":11, "keywords":["Perceived Teacher Confirmation", " Perceived Understanding", " Ratings of Instruction" ] },
	{ "eid":"2-s2.0-33846407630", "abstract":"Involvement has long been theoretically specified as a crucial factor determining the persuasive impact of messages. In social judgment theory, ego-involvement makes people more resistant to persuasion, whereas in dual-process models, high-involvement people are susceptible to persuasion when argument quality is high. It is argued that these disparate predictions might be reconciled by either different involvement types (i.e., value relevant vs. outcome relevant) or different attitude modification processes (i.e., attitude change vs. attitude formation). An experiment (N = 684) varying topic, position advocated, outcome relevance, and argument quality tested these moderators. The data were consistent with existence of two different types of involvement, but none of the theoretical predictions were consistent with the data. Instead, a main effect for argument quality had the largest impact on attitude change. Regardless of value-relevant involvement, outcome-relevant involvement, and attitude modification process, participants were more persuaded by high- rather than low-quality arguments, with boomerang effects observed for low-quality arguments. These findings highlight the importance of sound message design in persuasion. © 2007 International Communication Association.", "count":11, "keywords":[ ] },
	{ "eid":"2-s2.0-84855757338", "abstract":"The study reported here explored the social dimension of health-related blogs by examining blogging as a means to marshal social support and, as a result, achieve some of the health benefits associated with supportive communication. A total of 121 individuals who author a blog dedicated to their experience living with a specific health condition completed the study questionnaire. The number of blog posts made by respondents and proportion of posts with reader comments were positively associated with perceived social support from blog readers. The relationship between blog reader support and two outcomes related to well-being depended upon the support available in bloggers' strong-tie relationships with family and friends. Consistent with the social compensation (i.e., 'poor get richer') perspective, blog reader support was negatively associated with loneliness and positively associated with personal growth when support in strong-tie relationships was relatively lacking. © 2011 National Communication Association.", "count":11, "keywords":[ "Blog", " Communication technology", " Health communication", " Social support" ] },
	{ "eid":"2-s2.0-77954138063", "abstract":"Many U.S. adults hold fatalistic beliefs about cancer prevention despite evidence that a large proportion of cancer deaths are preventable. We report findings from two studies that assess the plausibility of the claim that local television (TV) news cultivates fatalistic beliefs about cancer prevention. Study 1 features a content analysis of an October 2002 national sample of local TV and newspaper coverage about cancer. Study 2 describes an analysis of the 2005 Annenberg National Health Communication Survey (ANHCS). Overall, findings are consistent with the claim that local TV news coverage may promote fatalistic beliefs about cancer prevention. We conclude with a discussion of study implications for cultivation theory and the knowledge gap hypothesis and suggest foci for future research. © 2010 International Communication Association.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-34250212950", "abstract":"In this study, demand/withdraw patterns and feeling caught were tested as mediators of family communication patterns and young adults' mental well-being. Participants included 567 young adults from divorced and nondivorced families. For young adults in nondivorced families, family conversation orientations had both a positive, direct effect on mental well-being and an indirect effect on well-being through witnessing marital demand/withdraw patterns and feeling caught. For young adults in divorced families, however, conversation orientations had only a direct, positive effect on well-being, whereas conformity orientations had a negative, indirect effect through witnessing demand/withdraw patterns. Interestingly, respondents from divorced families reported more feelings of being caught between their parents, yet such feelings predicted diminished well-being only for respondents from nondivorced families. © 2007 International Communication Association.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-34547474682", "abstract":"In this study, the degree to which young adults felt caught between their parents was tested as a mediator between marital conflict behaviors and young adults' mental health and family satisfaction. Participants included 1170 young adult children from first marriage and postdivorce families in four different states. Using structural equation modeling, the results revealed that parents' symbolic aggression, demand/withdraw patterns, and negative disclosures were positively associated with young adult children's feelings of being caught. Such feelings, in turn, were inversely associated with children's reports of family satisfaction and mental health. Although young adult children from divorced families witnessed, on average, more marital aggression, negative disclosures, and demand/withdraw patterns than those from nondivorced families, the associations in the model were relatively comparable across both family types. Further, tests of mediation revealed that feeling caught served primarily as a partial mediator for family satisfaction and as a full mediator for mental health, though such feelings suppressed the positive effect of parental disclosures on family satisfaction for children in nondivorced families. Finally, children's closeness with both parents moderated the associations in the model.", "count":10, "keywords":[ "Aggression", " Demand/withdraw patterns", " Disclosure", " Feeling caught", " Mental health" ] },
	{ "eid":"2-s2.0-33750076704", "abstract":"This study provided the first empirical test of point predictions made by the Park-Levine probability model of deception detection accuracy. Participants viewed a series of interviews containing truthful answers, unsanctioned, high-stakes lies, or some combination of both. One randomly selected set of participants (n = 50) made judgments where the probability that each message was honest was P(H)=.50. Accuracy judgments in this condition were used to generate point predictions generated from the model and tested against the results from a second set of data (n = 413). Participants were randomly assigned to one of eight base-rate conditions where the probability that a message was honest systematically varied from 0.00 to 1.00. Consistent with the veracity effect, participants in P(H)=.50 condition were significantly more likely to judge messages as truths than as lies, and consequently truths (67%) were identified with greater accuracy than lies (34%). As predicted by the model, overall accuracy was a linear function of message veracity base-rate, the base-rate induction explained 24% of the variance in accuracy scores, and, on average, raw accuracy scores for specific conditions were predicted to within approximately ± 2.6%. The findings show that specific deception detection accuracy scores can be precisely predicted with the Park-Levine model. © 2006 National Communication Association.", "count":10, "keywords":[ "Accuracy", " Deception", " Lies", " Lying", " Truth-bias" ] },
	{ "eid":"2-s2.0-33746578075", "abstract":"Research on digital divide phenomena has produced opposing theoretical frameworks. This study pits the disappearing digital divide approach against the emerging digital differentiation approach and empirically tests the validity of their predictions regarding adolescents' internet use and their tendency towards ubiquitous internetting. Multivariate analyses of a survey of 749 Dutch adolescents aged 13-18 showed that adolescents' unequal access to socio-economic and cognitive resources shaped their use of the internet as an information and an entertainment medium. Adolescents with greater socio-economic and cognitive resources used the internet more frequently for information and less often for entertainment than their peers with fewer socio-economic and cognitive resources. We found a similar pattern regarding adolescents' tendency towards ubiquitous internetting. The findings tentatively suggest that the emerging digital differentiation approach describes current digital divide phenomena more adequately than the disappearing digital divide approach. © 2006 Elsevier B.V. All rights reserved.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-34547529325", "abstract":"This study developed and tested an 'Internet-attribute- perception' model that explains how self-disclosure develops in instant messaging (IM) interactions. Following hyperpersonal communication theory, two attributes of computer-mediated communication (i.e., reduced nonverbal cues and controllability) were assumed to be responsible for increased online self-disclosure in IM. However, our model posed that any actual effects of these attributes would depend on users' perceptions of the relevance of these attributes. Furthermore, our model posed that these perceptions would mediate the relationship between personality characteristics (i.e., private and public self-consciousness, and social anxiety) and online selfdisclosure. Using structural equation modeling on a sample of 1,203 Dutch adolescents, we found that adolescents' perceptions of the relevance of reduced nonverbal cues and controllability encouraged their feelings of disinhibition, which in turn increased their online self-disclosure. As expected, private and public selfconsciousness and social anxiety stimulated adolescents' perceptions of the relevance of reduced nonverbal cues and controllability, but did not directly influence online self-disclosure. The study shows the vital role of users' perceptions of CMC attributes in Internet-effects research.", "count":10, "keywords":[ ] }, 
	{ "eid":"2-s2.0-23044479110", "abstract":"Reactance theory might be profitably applied to understanding failures in persuasive health communication but for one drawback: The developer of the theory contends that reactance cannot be measured. Rejecting this position, this paper develops four alternative conceptual perspectives on the nature of reactance (i.e., combinations of cognition and affect), then provides an empirical test of each. Two parallel studies were conducted, one advocating flossing (N = 196), the other urging students to limit their alcohol intake (N = 200). In both cases, a composite index of anger and negative cognitions fully mediated the effects of threat-to-freedom and trait reactance on attitude and intention. The data showed that, in fact, reactance can be operationalized as a composite of self-report indices of anger and negative cognitions. The implications for persuasive communication, in general, are considered as well the specific findings for flossing and drinking. © 2005 National Communication Association.", "count":52, "keywords":["Anger", " Persuasion", " Reactance", " Threat to Freedom" ]},
	{ "eid":"2-s2.0-31844450561", "abstract":"Mass media campaigns have long been a tool for promoting public health. How effective are such campaigns in changing health-related attitudes and behaviors, however, and how has the literature in this area progressed over the past decade? The purpose of the current article is threefold. First, I discuss the importance of health mass media campaigns and raise the question of whether they are capable of effectively impacting public health. Second, I review the literature and discuss what we have learned about the effectiveness of campaigns over the past 10 years. Finally, I conclude with a discussion of possible avenues for the health campaign literature over the next 10 years. The overriding conclusion is the following: The literature is beginning to amass evidence that targeted, well-executed health mass media campaigns can have small-to-moderate effects not only on health knowledge, beliefs, and attitudes, but on behaviors as well, which can translate into major public health impact given the wide reach of mass media. Such impact can only be achieved, however, if principles of effective campaign design are carefully followed. Copyright © Taylor & Francis Group, LLC.", "count":48, "keywords":[ ] },
	{ "eid":"2-s2.0-7244239529", "abstract":"Little is known about access, sources, and trust of cancer-related information, or factors that facilitate or hinder communication on a populationwide basis. Through a careful developmental process involving extensive input from many individuals and organizations, the National Cancer Institute (NCI) developed the Health Information National Trends Survey (HINTS) to help fill this gap. This nationally representative telephone survey of 6,369 persons aged >18 years among the general population was first conducted in 2002-2003, and will be repeated biennially depending on availability of funding. The purpose of creating a population survey to be repeated on a cyclical basis is to track trends in the public's rapidly changing use of new communication technologies while charting progress in meeting health communication goals in terms of the public's knowledge, attitudes, and behaviors. The HINTS survey instrument was built upon extant models of health communication and behavior change, taking into account the rapidly changing communication environment. Questions in the survey were drawn from an overall theoretical framework that juxtaposed the 'push' aspects of traditional broadcast media against the 'pull' aspects of new media. HINTS data will be made widely available for researchers and practitioners; it will help further research in health communication and health promotion and provide useful information for programs, policies, and practices in a variety of settings.", "count":42, "keywords":[ ] },
	{ "eid":"2-s2.0-35348870339", "abstract":"A meta-analytic review of 93 studies (N = 21,656) finds that in disease prevention messages, gain-framed appeals, which emphasize the advantages of compliance with the communicator's recommendation, are statistically significantly more persuasive than loss-framed appeals, which emphasize the disadvantages of noncompliance. This difference is quite small (corresponding to r = .03), however, and appears attributable to a relatively large (and statistically significant) effect for messages advocating dental hygiene behaviors. Despite very good statistical power, the analysis finds no statistically significant differences in persuasiveness between gain- and loss-framed messages concerning other preventive actions such as safer-sex behaviors, skin cancer prevention behaviors, or diet and nutrition behaviors. Copyright © Taylor & Francis Group, LLC.", "count":40, "keywords":[ ] },
	{ "eid":"2-s2.0-72949100083", "abstract":"Research has examined the ability of entertainment-education (E-E) programs to influence behavior across a variety of health and social issues. However, less is known about the underlying mechanisms that account for these effects. In keeping with the extended elaboration likelihood model (E-ELM) and the entertainment overcoming resistance model (EORM), we examined how story features, such as narrative transportation and involvement with characters, may reduce three forms of resistance to persuasion - reactance, counterarguing, and perceived invulnerability. In a between-subjects experiment, 367 undergraduates viewed either a dramatic narrative or a nonnarrative program about the difficult consequences of an unplanned teen pregnancy. Participants completed a questionnaire assessing their reactions to the program immediately after viewing and again 2 weeks later. Consistent with predictions derived from the EORM and E-ELM, the dramatic narrative reduced reactance by fostering parasocial interaction with characters and decreasing perceptions of persuasive intent. Also as expected, identification with characters in the narrative reduced counterarguing and increased perceived vulnerability to unplanned pregnancy - although the latter occurred only at the delayed posttest 2 weeks after exposure. Unexpectedly, transportation into the dramatic narrative was associated with greater counterarguing. Taken together, this research demonstrates that investigating narrative influence from the perspective of overcoming resistance is a useful approach. Findings also suggest important differences in how individuals process narrative and nonnarrative messages. © 2010 International Communication Association.", "count":40, "keywords":[ ] },
	{ "eid":"2-s2.0-33646019818", "abstract":"In this experiment, we examine effects of television dramas on support for controversial public policies (gay marriage and the death penalty) and explore mechanisms that may explain such effects. The dramas influenced support for death penalty but not gay marriage. As predicted, exposure to the relevant drama eliminated the relationship between prior ideology (conceptualized as a continuous variable) and death penalty support. Moreover, the valence of the relationship between prior (increasingly liberal) ideology and salience of a relevant value (perceived importance of a safe and crime-free society) went from negative in the comparison condition to positive after exposure to the relevant drama. These and other results suggest that a television narrative can influence policy support by reframing the dramatic situation to reduce the effect of prior ideology and values and by minimizing processing of the story as intentionally persuasive discourse. © 2006 International Communication Association.", "count":39, "keywords":[ ] },
	{ "eid":"2-s2.0-33745392194", "abstract":"Increasing information flow often leads to widening gaps in knowledge between different socioeconomic status (SES) groups as higher SES groups are more likely to acquire this new information at a faster rate than lower SES groups. These gaps in knowledge may offer a partial but robust explanation for differential risk behaviors and health disparities between different social groups. Drawing on the Health Information National Trends Survey (HINTS 2003), a national survey of communication behaviors conducted by the National Cancer Institute (NCI), we examine the relationship between publicity and knowledge gaps on two cancer topics that received different levels of publicity: knowledge about tobacco and sun exposure and their respective links to cancer. Analyses of the HINTS 2003 data suggest that differential knowledge levels of causes of cancer between SES groups are one potential explanation of cancer disparities that have been extensively reported in the literature. It is evident that high income and high education are associated with awareness about causes of major cancers such as lung and skin, and may allow people to protect themselves and minimize their risks. The data also show that heavier media attention could attenuate the knowledge gaps though moderate publicity or lack of news coverage may actually widen them. Last, the findings in this article suggest that it is necessary to take into account the SES variation within different racial and ethnic groups rather than mask them by treating the groups as one. Copyright © Taylor & Francis Group, LLC.", "count":32, "keywords":[ ] },
	{ "eid":"2-s2.0-0037374516", "abstract":"The Internet and World Wide Web are emerging as important public relations tools for both profit and non-profit organizations. Little evidence exists, however, about the extent to which new technologies help organizations build relationships with publics. This article examines the relationship between Web site design and organizational responsiveness to stakeholder information needs. Two organizational types with differing levels of resource dependency (general environmental activist and watchdog groups) are examined. Our analysis assesses each organizational type's general dialogic capacity as well as the responsiveness of the organizations to requests for information. © 2003 Elsevier Science Inc. All rights reserved.", "count":27, "keywords":[ ] },
	{ "eid":"2-s2.0-33746669267", "abstract":"This paper reviews and summarizes the literature on the relationship between emotion and persuasion as it bears on the production of cancer prevention and detection messages. A series of propositions are presented that serve to illustrate the intricacies of the emotion-persuasion relationship. These propositions deal with the necessary conditions for emotional arousal, individual differences in emotional reactivity to cancer messages, the potential for emotion-inducing messages to produce persuasive and counterpersuasive effects, the conditions that circumscribe the influence of emotions on persuasion, and the mechanisms by which that influence is achieved. To the extent that the literature permits, advice on message design is offered. © 2006 International Communication Association.", "count":27, "keywords":[ ] },
	{ "eid":"2-s2.0-72949120800", "abstract":"This article elaborates upon the notion of media enjoyment in the context of film viewing by proposing a complementary type of gratification that we conceptualize as appreciation. Three studies were conducted to tap into the multidimensionality of viewers' entertainment gratifications with a special focus on the domain of more serious, poignant, and pensive media experiences typically associated with genres such as drama, history, documentary, or art films. These studies provide evidence of and measurement for gratifications related to fun and suspense, but also gratifications related to moving and thought-provoking entertainment experiences, with all three gratifications leading to perceptions of entertainment having a more long-lasting or enduring effect. The results are discussed with regard to the theoretical conceptualization of entertainment gratification. © 2010 International Communication Association.", "count":26, "keywords":[ ] },
	{ "eid":"2-s2.0-34548792337", "abstract":"Can perceived message effectiveness (PE) be considered a cause of actual effectiveness (AE)? If so, PE judgments can be used as valid indicators of the persuasiveness of messages in the preimplementation phase of campaigns. In addition, manipulating PE may be a viable persuasive strategy. But, if the reverse causal sequence obtains (AE?PE), then the strategy would be ineffective and the utility of PE in formative campaign research meaningless. Structural equation analysis of 2 cross-sectional data sets (N = 202 and 204) concerned with fear appeals favored the PE?AE hypothesis. Two additional studies (N = 140 and 237), which employed a total of 13 public service announcements (PSAs), returned the same result. A fifth experimental study (N = 119) which utilized 2 PSAs provided further indication that PE?AE but not the reverse. At least under the conditions that characterize formative research, PE may be viewed as a causal antecedent of AE. © 2007 International Communication Association.", "count":25, "keywords":[ ] },
	{ "eid":"2-s2.0-33749999304", "abstract":"This study compares the news coverage of election campaigns in three Swedish newspapers at the time of the 2002 national election and three U.S. newspapers at the time of the 2004 presidential election. The results from the content analysis show that the metaframe of politics as a strategic game was more common in the U.S. newspapers, while the metaframe of politics as issues was more common in the Swedish newspapers. U.S. articles were also more likely to use the horse-race and political strategy frames. While U.S. coverage was predominantly descriptive in focus, an interpretive journalistic style was more often dominant in the Swedish articles. The results also show that the U.S. news stories were triggered by the words and actions of the campaigns more often than the Swedish news stories.", "count":24, "keywords":["Comparative political communication", " Election news coverage", " Framing", " Sweden" ] },
	{ "eid":"2-s2.0-37349044373", "abstract":"Although measures of perceived message effectiveness are commonly employed in formative evaluation research, the validity of such measures has been assumed rather than demonstrated. A meta-analysis revealed a corrected-for-attenuation correlation of .41 between perceived effectiveness (PE) and attitude (k=40). This association was apparently subject to the influence of moderator variables, although the pattern of influence was unstable across different types of analysis. Overall, the results empirically demonstrate the value of PE judgments in formative research and in circumstances in which actual effectiveness (AE) is difficult or impossible to measure. They also prompt a host of questions concerning (a) the causal relationship between PE and AE, (b) the possibility of bias in these judgments, and (c) the potential for developing methods to reduce or remove bias in effectiveness judgments. Future research is needed to corroborate these results as well as broaden the range of AE measures. © 2007 International Communication Association.", "count":23, "keywords":[ ] },
	{ "eid":"2-s2.0-41049108670", "abstract":"Four studies were conducted to explore how tender affective states (e.g., warmth, sympathy, understanding) predict attraction to entertainment that features poignant, dramatic, or tragic portrayals. Studies 1 and 2 found that tenderness was associated with greater interest in viewing sad films. Studies 3 and 4 found that tender affective states were associated with preferences for entertainment featuring not only sad portrayals but also entertainment featuring drama and human connection. Results are discussed in terms of how these forms of entertainment may provide viewers the opportunity to contemplate the poignancies of human life - an activity that may reflect motivations of media use related to meaningfulness or insight rather than only the experience of pleasure. © 2008 International Communication Association.", "count":23, "keywords":[ ] },
	{ "eid":"2-s2.0-65749086166", "abstract":"News reports of scientific research are rarely hedged; in other words, the reports do not contain caveats, limitations, or other indicators of scientific uncertainty. Some have suggested that hedging may influence news consumers' perceptions of scientists' and journalists' credibility (perceptions that may be related to support for scientific research and/or adoption of scientific recommendations). But whether hedging does affect audience perceptions is unknown. A multiple-message experiment (N = 601) found that across five messages, both scientists and journalists were viewed as more trustworthy (a) when news coverage of cancer research was hedged (e.g., study limitations were reported) and (b) when the hedging was attributed to the scientists responsible for the research (as opposed to scientists unaffiliated with the research). © 2008 International Communication Association.", "count":22, "keywords":[ ] },
	{ "eid":"2-s2.0-80053483578", "abstract":"The purpose of this research is to broaden the conceptualization of entertainment selection to identify not only pleasure-seeking (hedonic concerns) as a motivator, but to also recognize that individuals may choose media as a means of 'truth-seeking' (eudaimonic concerns). This article conceptualized and developed measures to illustrate that entertainment can be used as a means of experiencing not only enjoyment, but also as a means of grappling with questions such as life's purpose and human meaningfulness. 4 studies were conducted in the development of these measures, providing evidence for their validity in terms of entertainment preference and individual differences, and illustrating how these motivations predict preferences for entertainment that elicits unique affective experiences. © 2011 International Communication Association.", "count":22, "keywords":[ ] },
	{ "eid":"2-s2.0-33751529120", "abstract":"This study directly tests the hypothesis that secondary task reaction time (STRTs) measured during television viewing index available resources rather than resources allocated by the viewer, resources required by the message, or resources remaining in the system. An initial test of the hypothesis did not support the theoretical interpretation of STRTs as either available or remaining resources. A subsequent secondary analysis introduced a new measure of television message complexity called information introduced. The stimuli were recoded using this measure and reanalyzed to test the same hypothesis. Results of the secondary analysis yielded a pattern of STRT responses supporting the prediction that STRTs are indexing available resources. Copyright © 2006, Lawrence Erlbaum Associates, Inc.", "count":22, "keywords":[ ] },
	{ "eid":"2-s2.0-78149404062", "abstract":"This article presents a model of enjoyment rooted in self-determination theory that includes the satisfaction of three needs related to psychological well-being: autonomy, competence, and relatedness. In an experiment designed to validate this conceptualization of enjoyment, we manipulate video game characteristics related to the satisfaction of these needs and examine their relative effects on enjoyment. The validated model explains 51% of the variance in enjoyment, even without including needs usually studied in relation to enjoyment such as pleasure seeking. Results indicate the utility of defining enjoyment as need satisfaction. These results are discussed in terms of a broader conceptualization of enjoyment represented as the satisfaction of a comprehensive set of functional needs. © 2010 International Communication Association.", "count":21, "keywords":[ "Assessment", " Entertainment media", " Hedonism", " Psychological well-being", " Theory of self-determination" ] },
	{ "eid":"2-s2.0-34547413624", "abstract":"The effects of message framing on reactions to campaign messages promoting organ donation were examined in three experiments. It was predicted that gain-framed messages would produce more positive reactions toward organ and tissue donation. In Study 1, students (N=189) responded to either a gain-framed or loss-framed message about organ donation. Study 2 (N=318) and Study 3 (N=433) examined the role of psychological reactance as a mediator between framing and reactions. Results indicated an effect for framing across the three studies - specifically, students reading a gain-framed message reported more favorable reactions toward the scripted message and lower psychological reactance. Psychological reactance and perceived manipulative intent were found to mediate the relationship between framing and message reactions.", "count":19, "keywords":[ "Framing", " Organ", " Prospect theory", " Psychological reactance", " Reactions" ] },
	{ "eid":"2-s2.0-33646777753", "abstract":"Research on organ donation suggests a strong association between family discussions about the issue and final organ donor status. However, very few studies have examined the factors that influence individuals' willingness to talk directly to their family about this topic or the impact of these discussions. This investigation provides a partial test of a newly developed theory of information management to better understand the processes of family discussions about organ donation. Results from two studies generally support the utility of the theory in this context, suggest ways in which organ donation campaigns may improve their effectiveness, and recommend future directions for researchers in this area. Moreover, the data show differences across ethnic groups that support and extend past work in this area.", "count":18, "keywords":[ "Family Communication", " Information Seeking", " Organ Donation", " Uncertainty" ] },
	{ "eid":"2-s2.0-63649092774", "abstract":"Drawing on theories of social learning, social representations and the organ donation model, online surveys were used to examine the impact of organ donation storylines of 4 U.S. television dramas (CSI: NY, Numb3rs, House, and Grey's Anatomy) on viewers' attitudes, knowledge, and behaviors. Results revealed that viewers acquired knowledge from the content of each drama, despite the fact that some content was inaccurate. Viewers who were not organ donors prior to exposure to the dramas were more likely to decide to donate organs if the drama explicitly encouraged donation, portrayed characters revealing how they had become donors and discussed the merits of donating. Viewers were also more likely to become an organ donor if they were emotionally involved in the narrative. Implications for using dramas to educate and motivate the public were discussed. © 2009 International Communication Association.", "count":18, "keywords":[ ] },
	{ "eid":"2-s2.0-33845807001", "abstract":"This experimental study examined the effects of teacher self-disclosure via Facebook on anticipated college student motivation, affective learning, and classroom climate. Participants who accessed the Facebook website of a teacher high in self-disclosure anticipated higher levels of motivation and affective learning and a more positive classroom climate. In their responses to open-ended items, participants emphasized possible negative associations between teacher use of Facebook and teacher credibility. Participants offered recommendations for teachers regarding the use of Facebook and other weblog services.", "count":18, "keywords":[ "Affective learning", " Classroom climate", " College student motivation", " Teacher self-disclosure" ] },
	{ "eid":"2-s2.0-78651089731", "abstract":"Although mediatization as a term is commonly used in the academic literature, it is rarely defined well and there are almost no studies that explicitly seek to investigate the mediatization of politics. Drawing on the literature on mediatization, media interventionism, political news journalism and related areas, the purpose of this article is to develop indicators of the degree to which news content is mediatized, and test these in a comparative content analysis of how Swedish and US television news covered the 2006 Swedish and 2008 US election campaigns. The results show that election news on US television is more mediatized than that on Swedish television, as expected. However, few differences were found across commercial and public service television news within Sweden. The study also suggests that the mediatization of news content may be moderated by national journalism cultures, political news cultures and political communication cultures. © The Author(s) 2011.", "count":18, "keywords":[ "comparative research", " election news", " media interventionism", " mediatization" ] },
	{ "eid":"2-s2.0-35348930398", "abstract":"This paper examines whether emotional message content alters the effects of structural complexity and information density on available resources, measured by secondary task reaction times (STRTs), and message encoding, measured by audio recognition. In addition, hypotheses relating motivational activation and resource availability based on the motivational activation concepts of positivity offset (greater appetitive activation in a neutral environment) and negativity bias (faster aversive activation) influence are tested. Results replicate previous research supporting the contention that STRTs measure available resources. In addition, they show that the basic pattern of STRTs and recognition as a function of allocated and required resources is relatively consistent regardless of emotional content of the message. Emotion appears to function as a constant, increasing both resource allocation and resources required. Finally, these data provide some initial support for predicted relationships between motivational activation and resource allocation based on the constructs of positivity offset and negativity bias. Copyright © Lawrence Erlbaum Associates, Inc.", "count":18, "keywords":[ ] },
	{ "eid":"2-s2.0-53849130402", "abstract":"The present investigation sought to advance Psychological Reactance Theory (PRT) by examining whether trait reactance and sensation seeking influence the magnitude of a perceived threat, state reactance, and reactance restoration. Results revealed that high trait reactant (HTR) and low trait reactant (LTR) individuals and high sensation seekers (HSS) and low sensation seekers (LSS) processed persuasive messages similarly, adding credibility to recent PRT advances. Dogmatic and vivid language were perceived as a threat for most individuals. An interaction between dogmatic and vivid language on perceived threat was found for HTR and HSS for the sunscreen message. An indirect effect connecting language features and state reactance through perceived threat was supported. Regression analysis revealed that trait reactance and sensation seeking predict variables associated with state reactance. © 2008 International Communication Association.", "count":18, "keywords":[ ] },
	{ "eid":"2-s2.0-79951893571", "abstract":"Contrasting hypotheses were posed to test the effect of Facebook exposure on self-esteem. Objective Self-Awareness (OSA) from social psychology and the Hyperpersonal Model from computer-mediated communication were used to argue that Facebook would either diminish or enhance self-esteem respectively. The results revealed that, in contrast to previous work on OSA, becoming self-aware by viewing one's own Facebook profile enhances self-esteem rather than diminishes it. Participants that updated their profiles and viewed their own profiles during the experiment also reported greater self-esteem, which lends additional support to the Hyperpersonal Model. These findings suggest that selective self-presentation in digital media, which leads to intensified relationship formation, also influences impressions of the self. Copyright 2011, Mary Ann Liebert, Inc.", "count":17, "keywords":[ ] },
	{ "eid":"2-s2.0-78650977525", "abstract":"This investigation tested a theoretical model of communication behavior with specific Facebook friends, such that attitudes toward (a) online self-disclosure, and (b) online social connection, predict Facebook communication frequency and, in turn, relational closeness. Participants included both undergraduates and older adults. Results generally supported the model, with the interaction effect between self-disclosure and social connection directly predicting Facebook communication and indirectly predicting relational closeness. For both dependent variables, online social connection was a positive predictor at low and moderate levels of online self-disclosure, but high levels reduced the association to nonsignificance. One implication of these results was that high-warrant information may discourage those with social anxiety from social network site communication. © The Author(s) 2011.", "count":16, "keywords":[ "attitude", " closeness", " Facebook", " online communication", " social network sites" ] },
	{ "eid":"2-s2.0-39149093371", "abstract":"This essay conducts an analysis of blogs as public relations tools. Following an overview of blogs, attention is given to how blogs can be used more effectively by public relations professionals, and how blogs are favored by communication firms and consultants as essential public relations tools. The essay concludes that while blogs have incredible potential as research, framing, and persuasion tools, their utility as a public relations tool is currently limited. © 2008 Elsevier Inc. All rights reserved.", "count":16, "keywords":[ "Blog", " Blogging", " Critical", " News technology", " Public relations", " RSS" ] },
	{ "eid":"2-s2.0-61649086701", "abstract":"The purpose of the current study was to conduct a 10-year systematic review of HIV/AIDS mass communication campaigns focused on sexual behavior, HIV testing, or both (1998-2007) and to compare the results with the last comprehensive review of such campaigns, conducted by Myhre and Flora (2000). A comprehensive search strategy yielded 38 HIV/AIDS campaign evaluation articles published in peer-reviewed journals, representing 34 distinct campaign efforts conducted in 23 countries. The articles were coded on a variety of campaign design and evaluation dimensions by two independent coders. Results indicated that compared with the previous systematic review (1986-1998 period), campaigns increasingly have employed the following strategies: (1) targeted defined audiences developed through audience segmentation procedures; (2) designed campaign themes around behavior change (rather than knowledge change); (3) used behavioral theories; (4) achieved high message exposure; (5) used stronger research designs for outcome evaluation; and (6) included measures of behavior (or behavioral intentions) in outcome assessments. In addition, an examination of 10 campaign efforts that used more rigorous quasi-experimental designs revealed that the majority (8 of 10) demonstrated effects on behavior change or behavioral intentions. Despite these positive developments, most HIV/AIDS campaigns continue to use weak (i.e., preexperimental) outcome evaluation designs. Implications of these results for improved design, implementation, and evaluation of HIV/AIDS campaign efforts are discussed. Copyright © Taylor & Francis Group, LLC.", "count":15, "keywords":[ ] },
	{ "eid":"2-s2.0-79551478792", "abstract":"This study was designed to further our understanding of the central role of motivational activation in mediated information processing and media choice. To do this, a dynamic model was developed to formalize the dynamic effects of three basic motivational input variables (arousing content, positivity, and negativity) on four physiological output measures (heart rate, skin conductance level, corrugator activity, and zygomatic activity) and a behavioral choice measure of television channel selection. The input and output variables were selected based on extensive theoretical and empirical research that has explicated static relationships among these variables. In general, the findings of the dynamic modeling approach were consistent with the previous literature using traditional static statistical methods. However, this study also theoretically extended the previous work. © 2011 International Communication Association.", "count":15, "keywords":[ ] },
	{ "eid":"2-s2.0-33745422897", "abstract":"Few nationally representative surveys have assessed the cancer-related information seeking behavior of the American public. Data for our analysis were from the 2003 Health Information National Trends Survey (HINTS). The goals of our analysis were to characterize cancer information seekers (3,011) and nonseekers (3,348) in terms of sociodemographic, health care access, and health status variables, and to describe the nature of the cancer-related information being sought by information seekers. Significant and independent associations with seeking status were identified for gender, age, race, income, education, personal and family history of cancer, and having a usual source of health care. Information seekers were less likely to be male (OR=.51); aged 65 or older (OR=.40); Hispanic (OR=.60); to have a usual source of health care (OR=.70); and more likely to have incomes greater than $50,000 (OR=1.50), some college (OR=1.87) or a college degree (OR=2.95), a prior cancer diagnosis (OR=3.57), or a family history of cancer (OR=2.17). Among cancer information seekers, the most frequently searched topic was cancer site-specific information (50.2%). Individuals who reported searching for cancer site-specific information were most frequently looking for information about breast cancer (23.8%), prostate cancer (11.5%), and skin cancer (11.3%). The HINTS survey provides a unique opportunity to explore the characteristics of information seekers and nonseekers and the content of information being sought by the public in a nationally representative sample; understanding gained from this effort provides generalizable and policy-relevant information about the American public's information needs. Copyright © Taylor & Francis Group, LLC.", "count":15, "keywords":[ ] },
	{ "eid":"2-s2.0-33644842930", "abstract":"In the context of adolescent smoking adoption, this study examined the presumed influence hypothesis, a theoretical model suggesting that smoking-related media content may have a significant indirect influence on adolescent smoking via its effect on perceived peer norms. That is, adolescents may assume that smoking-related messages in the mass media will influence the attitudes and behaviors of their peers and these perceptions in turn can influence adolescents' own smoking behaviors. Analyzing data from a sample of 818 middle school students, we found that both pro- and antismoking messages indirectly influenced smoking susceptibility through their perceived effect on peers. However, this indirect effect was significantly stronger for prosmoking messages than for antismoking messages, an outcome that most likely increases adolescents' susceptibility to cigarettes. © 2006 International Communication Association.", "count":14, "keywords":[ ] },
	{ "eid":"2-s2.0-53849090254", "abstract":"This article presents findings from the first study of cancer news coverage in a national sample of Black and general-audience newspapers. We compared 2,439 health news stories from 23 weekly Black newspapers to 2,767 health news stories from a constructed week sample of 12 daily general-audience newspapers, both collected between April 1, 2004, and March 31, 2005. Analyses examined differences in the amount and nature of cancer coverage, specifically cancer sites, disparities, localization, and personally mobilizing health information for readers. Cancer was the main topic in a higher proportion of health stories in Black newspapers than in general-audience newspapers (13.6% vs. 9.6%; p =.001). Among cancer stories, those in Black newspapers had more localization (p =.004), disparity information (p =.001), and personal mobilization information (p =.001) than those in general-audience newspapers. In neither type of newspaper did the distribution of stories by cancer site accurately reflect the impact of different cancers on population mortality. Copyright © Taylor & Francis Group, LLC.", "count":14, "keywords":[ ] },
	{ "eid":"2-s2.0-77954387025", "abstract":"This article examines one issue in how public relations students are socialized in their understanding of the value and power of social media in the practice of public relations. The public relations academic research about social media is explored, as well as the professional claims about the value of social media as a public relations tactic. The researchers conducted a content analysis of 1 year of Public Relations Tactics issues. The data are viewed through the theoretical frame of the socialization literature (Jablin, 1987). The results suggest that claims of social media power far outweigh evidence of social media effectiveness as a communication tool. A disconnect exists between what authors of Public Relations Tactics pieces view as the potential for social media and the research findings about the effectiveness of social media. The final section of the article discusses the implications for public relations educators, professional associations, and practitioners as they consider social media tactics in public relations strategy. © 2010 Elsevier Inc.", "count":13, "keywords":[ "Education", " New media technology", " Practice", " Socialization" ] },
	{ "eid":"2-s2.0-31644438886", "abstract":"Communication within recreational computer-mediated settings has received less attention than interaction in instrumental and organizational contexts. The present study compared the socioemotional and task-oriented content of 5,826 text messages produced by participants of an online video game. The results suggest that participants produced significantly more socioemotional than task content. Consistent with predictions flowing from Social Information Processing Theory, the vast majority of messages were socioemotional and positively valenced, despite the ostensible game objective of fighting other participants. Experience level played an important role in message production. More experienced participants produced both more positive and fewer negative socio-emotional messages than the less experienced and used more specialized language conventions (e.g., emoticons, scripted emotes, and abbreviations). The results are discussed in the context of previous research examining the effect of communication medium and interaction purpose on socioemotional and task message production. © 2006 Sage Publications.", "count":13, "keywords":[ "Computer experience", " Computer-mediated communication", " Interaction process analysis", " Social information processing", " Socioemotional and task communication", " Video games" ] },
	{ "eid":"2-s2.0-79952918491", "abstract":"This investigation examines how video game interactivity can affect presence and game enjoyment. Interactivity in the form of natural mapping has been advocated as a possible contributor to presence experiences, yet few studies to date have investigated this potential. The present work formulates a preliminary typology of natural mapping and addresses how several types of mapping impact the experience of a video game, with the expectation that more natural mapping leads to increased spatial presence affecting enjoyment. Two studies were conducted. In the first study, 48 participants played a golfing video game using one of two controller types (Nintendo Wiimote or gamepad). In the second, 78 participants played a driving video game using an even more natural controller (steering wheel) or one of three other controller types. Participants then completed measures of perceived naturalness, presence, and enjoyment. Results of both studies were generally consistent with expectations. © The Author(s) 2011.", "count":12, "keywords":[ ] },
	{ "eid":"2-s2.0-0037374191", "abstract":"A content analysis with an interrupted time-series design assessed the impact of an international public relations campaign launched by the Chinese government in the United States. The extent and nature of coverage of China in major US newspapers, particularly the New York Times, during and after the campaign suggest that the press appeared to have been affected by the campaign. This study explored a rarely tapped domain of public relations research, international public relations by state governments, and added to the literature of effectiveness evaluation of public relations and its methods. © 2003 Elsevier Science Inc. All rights reserved.", "count":12, "keywords":[ ] },
	{ "eid":"2-s2.0-73949098070", "abstract":"Despite the major importance of the news media's election news coverage, there are still only a few cross-national studies on how the media cover elections. There are even fewer that include both newspapers and TV news and that probe possible antecedents of how the media frame politics in their election news. Against this background, this article compares the media framing of election news in two countries-Belgium and Sweden- that constitute highly similar cases and both belong to the democratic corporatist model of media and politics. The study focuses on the importance of media channels, media types, and commercialism as antecedents of the media's framing of election news. © 2010 SAGE Publications.", "count":11, "keywords":[ "Comparative research", " Election news", " Media framing", " Newspapers", " Television news" ] },
	{ "eid":"2-s2.0-33745727332", "abstract":"The purpose of this study was to quantitatively synthesize the growing literature on the relationship between safer sexual communication (SSC) among sexual partners and condom use, and to systematically examine a number of conceptual and methodological moderators of this relationship. Data from 53 articles published in 27 journals met criteria for the study. Fifty-five independent effect sizes coded from samples totaling N = 18,529 were meta-analyzed. Results indicate that the mean sample-size weighted effect size of the SSC-condom use relation was r = .22, and a number of conceptual variables were found to moderate this relationship. Specifically, communication about condom use ( r = .25) and sexual history ( r = .23) had significantly ( p < .05) larger effect sizes than communication about safer sex (r=.18). In addition, SSC measures operationalized differently had significantly (p<.05) different effect sizes. From largest to smallest, these were behavioral format (r=.29), intentional format (r=.18), and self-efficacy format (r=.13). Measures that tried to assess persuasion attempts as compared with informational exchanges were not found to have significantly different effect sizes (p>.05). Further, methodological moderators tended to be unrelated to effect size. Implications for the future study of safer sexual communication as well as the importance of emphasizing communication skills in HIV preventive interventions are discussed. Copyright © Taylor & Francis Group, LLC.", "count":11, "keywords":[ ] },
	{ "eid":"2-s2.0-33846666765", "abstract":"This article reports the results of two studies designed to compare predictors of enjoyment of reality-based and fictional television programming. In Study 1, 260 adults completed a survey of their cognitive and emotional reactions to either the fictional or reality-based programming that they generally watch. In Study 2, 502 adults completed a similar survey but with a particular reality-based or fictional program in mind. Results suggest first that though voyeurism (i.e., curiosity about others) appears to be a key distinguishing gratification between reality and fictional programming, it is not always a predictor of reality television enjoyment. Indeed, many predictors of enjoyment, like happiness, parasocial relationships, social comparison, self-awareness, negative outcome, and dramatic challenge, varied as much among types of reality programs as between reality and fiction. Of particular interest, three variables - learning, suspense, and transportation - had opposite effects on enjoyment, depending on their programming context. The implications of these findings, as well as the role of perceived realism and our ability to explain more variance in enjoyment of reality versus fictional programming, are addressed. Apart from its insight into the reality television phenomenon, this research helps to more clearly articulate the cognitive and emotional underpinnings of enjoyment and further offers a unique theoretical perspective on the connection between the uses and gratifications paradigm and the construct of enjoyment. Copyright © 2006, Lawrence Erlbaum Associates, Inc.", "count":11, "keywords":[ ] },
	{ "eid":"2-s2.0-77952511942", "abstract":"There are several noteworthy debates associated with the study of emotion. For example, which comes first*emotion or cognition? Or, even more basic, what feature most centrally defines emotion? Although undoubtedly conceptually important, the more pressing question for scholars within our discipline is: which approach to emotion is most useful for understanding communication-based phenomena*the discrete or the dimensional view? Here I argue that, although these two perspectives share some very basic root elements, we must look for the best match between the phenomena under consideration and the unique strengths of the theoretical paradigms applied to them. Given the complexity of communicationrelated processes and outcomes, the more complex orientation to the study of emotion*the discrete emotion perspective*is most useful as what little might be lost in parsimony is more than offset by the precision gained in prediction. In this essay, I will first define emotion and the two major approaches to its study. I will then argue that given that unique emotion states (generated by unique appraisal patterns) are the key motivator behind differences in human thought, word, and deed, it is most reasonable to adopt a discrete perspective to the extent those outcomes are of interest. I will then present evidence from several domains of literature to demonstrate the value of the discrete over the dimensional view in the study of communication-related issues. © 2010 National Communication Association.", "count":11, "keywords":[ ] },
	{ "eid":"2-s2.0-84870592803", "abstract":"The primary aim of this study was to evaluate the extent to which news story format (narrative vs. non-narrative) can initiate empathic processes that produce more favorable evaluations of stigmatized groups. Participants (N = 399) read one of two versions of a story that described health care-related dilemmas for either immigrants, prisoners, or the elderly. Narrative-formatted stories produce more compassion toward the individuals in the story, more favorable attitudes toward the group, more beneficial behavioral intentions, and more information-seeking behavior. © 2012 AEJMC.", "count":11, "keywords":[ "empathy", " narratives", " news stories", " stigmatization" ] },
	{ "eid":"2-s2.0-46049100390", "abstract":"The present study uses a public commitment framework to examine how computer-mediated self-presentations can alter identities. Participants were asked to present with one of two traits, extroversion or introversion, in public or private computer-mediated communication. Public presentations were online, whereas private presentations took place in a text document. Only participants that presented themselves publicly internalized the trait presentation, suggesting that identity shift took place. Public self-presentations also contained more certain and definite forms of language than private self-presentations, suggesting that audiences evoke a more committed form of self-presentation. The findings in this research have important implications for the self-construction of identity online, particularly for individuals that use the Internet as a tool for public self-presentation, such as dating sites, social network sites, or blogs. Also, the findings highlight opportunities for theoretical development on identity construction as a function of computer-mediated communication. Copyright © Taylor & Francis Group, LLC.", "count":11, "keywords":[ ] },
	{ "eid":"2-s2.0-77956361509", "abstract":"The present study applies psychological reactance theory (PRT) to examine the effectiveness of a 2 (frame: gain, loss)2 (efficacy: present, not present) experiment to determine best practices in dissuading excessive alcohol consumption among college students. Results from the structural model revealed no association between a perceived threat to choose and message frame or efficacy appeals. As anticipated, a perceived threat to freedom was positively associated with state reactance, which in turn was positively associated with a boomerang effect and negatively associated with favorable source appraisal. State reactance was not associated with favorable attitudes toward preventing the overconsumption of alcohol. In addition to main effects, interactions between message frame and efficacy appeal with four person factors (participant age, trait reactance, perceived health risk, and alcohol consumption) were examined. Individuals perceiving health risk to be low would benefit from gain-frame messages, whereas loss-frame messages would be most effective for heavy drinkers. Finally, when communicating to underage drinkers, our results support using efficacy appeals when accompanied by a loss-frame message. © 2010 Taylor & Francis Group, LLC.", "count":11, "keywords":[ ] },
	{ "eid":"2-s2.0-35348986948", "abstract":"This investigation examines the extent to which interactive social agent technology can influence social presence, information processing, and persuasion. Specifically, it looks at how interactive media using virtual agents can increase the sensation of social presence, or the extent to which a person feels 'with' a mediated being. Using logic based on the Heuristic Systematic Model (HSM), social presence is posited to impact indicators of heuristic and systematic processing, leading to changes in attitude and intention toward a health issue. A 2 × 2 between subjects experiment was conducted (N = 125) with manipulations of interactivity (interactive or not) and source attractiveness (attractive or unattractive). Results of causal model tests suggest that interactive agents facilitate social presence leading to increased message processing, which in turn affects both attitude and behavioral intentions toward the issue of healthy blood pressure. Contrary to expectations, however, social presence with an unattractive source did not impede attitude and intentions. These findings are interpreted in light of presence, new media, and HSM scholarship. Copyright © Lawrence Erlbaum Associates, Inc.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-84861943454", "abstract":"This study attempted to (a) extend traditional mood management theory research by investigating the influence of the intrinsic needs for competence and autonomy on selective exposure to video games and (b) test the influence of satisfying these needs on resultant mood repair. An experiment varied satisfaction of competence and autonomy needs using false feedback. Subjects then selected media that varied in level of user demand. Measures of need satisfaction were taken before and after media selection. Results demonstrated that (a) thwarted intrinsic needs significantly predict the choice of video games with different levels of user demand and (b) the satisfaction of these needs predicts enjoyment. Findings indicate that mood management can result from mood repair through need satisfaction. © 2012 International Communication Association.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-57849137476", "abstract":"In this study, both face-to-face and online relational maintenance behaviors were tested as mediators of family communication patterns and closeness with a same-sex friend. Participants included 417 young adults recruited from communication courses at a large university in the Midwestern United States. The obtained structural model demonstrated that family communication patterns are associated with friendship closeness though face-to-face and online maintenance behaviors fully mediate this association. Specifically, young adults from high-conversation-orientation families engage in more face-to-face maintenance behaviors, which are positively associated with friendship closeness. These findings inform understanding of how family communication patterns influence extrafamilial relationships, suggesting that parents' cognitions and communication behaviors are associated with children's social well-being. © 2009 International Communication Association.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-49649119084", "abstract":"This study explores the relationship between cancer newspaper coverage and public knowledge about cancer prevention, confirming self-reported associations between news exposure and cancer prevention knowledge with descriptions of newspaper coverage of modifiable cancer risks. Content analyses (N = 954) revealed that newspapers pay relatively little attention to cancer prevention. However, there is greater newspaper attention to tobacco and diet than to exercise, sun, and alcohol. Survey analysis (the National Cancer Institute's Health Information National Trends Survey) revealed that after controlling for differences based on gender, race, age, income, and education, attention to health news was significantly associated with knowledge about cancer risks associated with food and smoking but not for knowledge about exercise, sun, or alcohol. These findings conform to the findings of the content analysis data and provide a validation of a self-reported measure of media exposure, as well as evidence suggesting a threshold below which news coverage may not generate public knowledge about cancer prevention. Copyright © Taylor & Francis Group, LLC.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-79957462071", "abstract":"Past research has demonstrated that news coverage of cancer research, and scientific research generally, rarely contains discourse-based hedging, including caveats, limitations, and uncertainties. In a multiple message experiment (k=4 news stories, N=1082), the authors examined whether hedging shaped the perceptions of news consumers. The results revealed that participants were significantly less fatalistic about cancer (p=.039) and marginally less prone to nutritional backlash (p=.056) after exposure to hedged articles. Participants exposed to articles mentioning a second researcher (unaffiliated with the present study) exhibited greater trust in medical professions (p=.001). The findings provide additional support for the inclusion of discourse-based hedging in cancer news coverage and suggest that news consumers will use scientific uncertainty in illness representations. © Taylor and Francis Group, LLC.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-84887114492", "abstract":"This article explores how technology and our recent access to, and abundance of, information, are affecting democracy, and the role of public relations professionals in a post mass media society. The article reviews pros and cons of new technology, discusses how public relations can improve, democracy using dialogue, communitarianism, and Long Now thinking, and discusses how to actually, use social media dialogically. The article argues that as public relations revives its conceptualization of, relationship, communication professionals also benefit democracy and society as a whole. © 2013 Elsevier Inc.", "count":10, "keywords":["Communitarianism", " Dialogic", " Dialogue", " Long Now", " Social media", " Technology" ] },
	{ "eid":"2-s2.0-33750854124", "abstract":"Testing hypotheses derived from regret and mood management theories, this research explores how regretted experiences impact interest in viewing experience-relevant TV programming and such viewing's effects on program enjoyment and felt regret. One hundred and forty-four participants, half of whom had been unfaithful in romantic relationships, were asked first to rate their interest in viewing a series of storylines and then to provide their reactions to 1 of 2 versions of a TV program depicting cheating behavior. Largely consistent with hypotheses, results indicated that those who had both cheated and felt regret about their behavior were more likely than others to want to watch experience-related storylines, were no less likely to enjoy watching such programming, and particularly preferred viewing the program version in which the main character rationalized, rather than expressed regret for, her behavior. Both program versions, however, reduced regret equally. A survey of 206 city residents also offered evidence consistent with predictions based on regret theory. Overall, this research speaks to the value of integrating theories of emotion with media theory to enhance the latter's predictive ability. © 2006 International Communication Association.", "count":10, "keywords":[ ] },
	{ "eid":"2-s2.0-33745393901", "abstract":"The decades surrounding the turn of the millennium will be remembered as a time of extraordinary opportunity in cancer communication. In 1990, the number of ageadjusted deaths due to cancer in the U.S. population began a slow steady decline after a century of disparaging increase. Reasons for this decline have been attributed to long-awaited successes in primary prevention, especially related to tobacco, and early detection for cervical, breast, prostate, and colorectal cancers, as well as advances in treatment. This was also a time of unparalleled change in the cancer communication environment. Scientific health discoveries escalated with the completion of the Human Genome project in 2003, and penetration of the Internet made health information available directly to consumers. To seize the opportunity afforded by these changes, the National Cancer Institute (NCI) launched the Health Information National Trends Survey (HINTS). Fielded for the first time in 2003, the HINTS is a nationally representative, general population survey of noninstitutionalized adults in the United States 18 years and older. This supplement contains a compilation of original research conducted using the data generated by the first administration of the HINTS telephone interviews. Covering topics in cancer knowledge, cancer cognition, risk perception, and information seeking, the articles represent an interdisciplinary view of cancer communication at the turn of the millennium and offer insight into the road ahead. Copyright © Taylor & Francis Group, LLC.", "count":10, "keywords":[ ] } 
	
	]

d3.json(thfill, function (error,json) {

	  function tabulate(json, columns) {
		  var sortAscending = true
			var table = d3.select('body').append('table')
			var thead = table.append('thead')
			var	tbody = table.append('tbody')
			.on('dblclick', function(d) {
    console.log('open tab')
    window.open(
      'wordcloud.jsp',
    );
  });;

			// append the header row
			thead.append('tr')
			  .selectAll('th')
			  .data(columns).enter()
			  .append('th')
			    .text(function (column) { return column; })
			    .on('click', function (d) {
		                	   thead.attr('class', 'header');
		                	   
		                	   if (sortAscending) {
		                	     rows.sort(function(a,b) { return b[d] < a[d]; });
		                	     sortAscending = false;
		                	     this.className = 'aes';
		                	   } else {
		                		 rows.sort(function(a,b) { return b[d] > a[d]; });
		                		 sortAscending = true;
		                		 this.className = 'des';
		                	   } });

			// create a row for each object in the data
			var rows = tbody.selectAll('tr')
			  .data(json)
			  .enter()
			  .append('tr');

			// create a cell in each row for each column
			var cells = rows.selectAll('td')
			  .data(function (row) {
			    return columns.map(function (column) {
			      return {column: column, value: row[column]};
			    });
			  })
			  .enter()
			  .append('td')
			    .text(function (d) { return d.value; });
			

		  return table;
		}

		// render the table(s)
		tabulate(thfill, ["eid","abstract","keywords","count"]); 
		
});

</script>
</body>
</html>